version: '3'
services:
  db:
    image: mysql:8.0.34-debian
    container_name: payana-db
    restart: always
    ports:
    - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'payanadb'
      MYSQL_USER: 'payana_user'
      MYSQL_PASSWORD: 'secret-payana'
      MYSQL_ROOT_PASSWORD: 'secret-root'
